"""Canonical-turn contracts shared by production and preview paths."""

from .contracts import (
    CAPABILITY_ALLOWLIST,
    STRUCTURED_CLAUSE_CAPABILITY_ALLOWLIST,
    CanonicalGoal,
    CanonicalTurnRequest,
    ClauseAction,
    ClauseSource,
    CurrentUtteranceParse,
    EntitySpan,
    GoalAuthorizationDecision,
    GoalExecutionStatus,
    GoalReadinessDecision,
    GoalSourceResolution,
    PendingBinding,
    PendingClarification,
    PendingSourceBinding,
    PendingTransitionProposal,
    StructuredClause,
    TurnCommand,
    TurnEvent,
    TurnResult,
)

__all__ = [
    "CAPABILITY_ALLOWLIST",
    "STRUCTURED_CLAUSE_CAPABILITY_ALLOWLIST",
    "CanonicalGoal",
    "CanonicalTurnRequest",
    "ClauseAction",
    "ClauseSource",
    "CurrentUtteranceParse",
    "EntitySpan",
    "GoalAuthorizationDecision",
    "GoalExecutionStatus",
    "GoalReadinessDecision",
    "GoalSourceResolution",
    "PendingBinding",
    "PendingClarification",
    "PendingSourceBinding",
    "PendingTransitionProposal",
    "StructuredClause",
    "TurnCommand",
    "TurnEvent",
    "TurnResult",
]
