"""Declarative rules for deterministic canonical-turn parsing.

This module intentionally contains data only. Rule evaluation belongs to the
entity and clause parser modules.
"""

RULE_CATALOG = (
    {
        "rule_id": "entity.fault_code.shape.v1",
        "category": "fault_code_shape",
        "pattern": r"(?<![A-Za-z0-9])([A-Za-z]{1,3}\d{4,6})(?![A-Za-z0-9])",
        "semantic_value": "fault_code",
        "priority": 700,
        "confidence": 1.0,
        "allowed_clause_roles": ("slot",),
        "capture_group": 1,
        "normalizer": "uppercase",
        "example": "A07089",
    },
    {
        "rule_id": "entity.device.motor_reference.v1",
        "category": "device_pattern",
        "pattern": r"(?<![A-Za-z0-9])(?:[A-Za-z]\d{2,4})?\s*电机\s*\d+(?!\d)",
        "semantic_value": "device_reference",
        "priority": 690,
        "confidence": 1.0,
        "allowed_clause_roles": ("slot",),
        "flags": "IGNORECASE",
        "normalizer": "remove_spaces",
        "example": "G120电机2",
    },
    {
        "rule_id": "entity.time.relative_window.v1",
        "category": "time_pattern",
        "pattern": (
            r"(?:最近|过去|近)\s*(?:\d+|[一二两三四五六七八九十半]+)\s*(?:分钟|小时|天|周)|"
            r"(?:今天|当前|现在|此刻)"
        ),
        "semantic_value": "time_window",
        "priority": 680,
        "confidence": 1.0,
        "allowed_clause_roles": ("slot",),
        "attributes": {"relative": True},
        "example": "最近一小时",
    },
    {
        "rule_id": "entity.artifact.explicit_reference.v1",
        "category": "artifact_reference",
        "pattern": r"(?<![A-Za-z0-9])(?:artifact|analysis|report|diagnosis):[A-Za-z0-9._:-]+",
        "semantic_value": "artifact_reference",
        "priority": 670,
        "confidence": 1.0,
        "allowed_clause_roles": ("source",),
        "flags": "IGNORECASE",
        "attributes": {"explicit": True},
        "example": "analysis:case-7",
    },
    {
        "rule_id": "source.prior_result.marker.v1",
        "category": "source_marker",
        "pattern": r"(?:刚才|上一轮|上一次|前面|之前|这个|该)(?:的)?(?:诊断(?:结果)?|分析结果|运行报告|报告|数据|结果)",
        "semantic_value": "source_reference",
        "priority": 660,
        "confidence": 1.0,
        "allowed_clause_roles": ("source",),
        "attributes": {"historical": True},
        "example": "刚才的诊断结果",
    },
    {
        "rule_id": "reference.correction.marker.v1",
        "category": "correction_marker",
        "pattern": r"(?:不是.+?是|改成|更正为|应该是)",
        "semantic_value": "correction_reference",
        "priority": 650,
        "confidence": 1.0,
        "allowed_clause_roles": ("reference",),
        "example": "改成",
    },
    {
        "rule_id": "reference.deictic.marker.v1",
        "category": "deictic_marker",
        "pattern": r"(?:它|这个|那个|该设备|刚才|上一轮|上一次|前面|之前)",
        "semantic_value": "deictic_reference",
        "priority": 640,
        "confidence": 1.0,
        "allowed_clause_roles": ("reference",),
        "example": "它",
    },
    {
        "rule_id": "clause.boundary.punctuation.v1",
        "category": "clause_boundary",
        "pattern": r"[，,。；;！？!?]+",
        "semantic_value": "boundary",
        "priority": 600,
        "confidence": 1.0,
        "allowed_clause_roles": ("boundary",),
        "example": "，",
    },
    {
        "rule_id": "clause.linker.leading.v1",
        "category": "linker",
        "pattern": r"^(并且|并|然后|同时|顺便|再|另外|以及)\s*",
        "semantic_value": "leading_linker",
        "priority": 590,
        "confidence": 1.0,
        "allowed_clause_roles": ("linker",),
        "capture_group": 1,
        "example": "顺便生成报告",
    },
    {
        "rule_id": "validation.model.forbidden_execution_content.v1",
        "category": "model_validation",
        "pattern": r"(?:\bsql\b|\bnode\b|\btool\b|\bpermission\b|\bauthori[sz](?:e|ation|ed)\b|权限|授权|工具名?|节点名?)",
        "semantic_value": "forbidden_execution_or_authorization_content",
        "priority": 1000,
        "confidence": 1.0,
        "allowed_clause_roles": ("validation",),
        "flags": "IGNORECASE",
        "example": "SQL tool authorization granted",
    },
    {
        "rule_id": "action.report.generate.v1",
        "category": "action_predicate",
        "pattern": r"(?:生成|整理成|出一份|制作).{0,6}(?:运行)?报告",
        "semantic_value": "generate_report",
        "priority": 900,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("*",),
        "example": "生成运行报告",
    },
    {
        "rule_id": "action.recommendation.request.v1",
        "category": "action_predicate",
        "pattern": r"(?:处理建议|处置建议|解决建议|怎么处理|如何处理|给出.{0,4}建议)",
        "semantic_value": "resolution_recommendation",
        "priority": 890,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("device_reference",),
        "example": "给出处理建议",
    },
    {
        "rule_id": "action.runtime.compare.v1",
        "category": "action_predicate",
        "pattern": r"(?:对比|比较).{0,12}(?:状态|运行|异常|数据)",
        "semantic_value": "compare_runtime_status",
        "priority": 880,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("device_reference",),
        "example": "对比运行状态",
    },
    {
        "rule_id": "action.diagnosis.assess.v1",
        "category": "action_predicate",
        "pattern": r"(?:诊断(?!结果)|判断).{0,12}(?:故障|异常|问题|原因)|(?:有没有|是否|存在).{0,5}故障",
        "semantic_value": "diagnose_fault",
        "priority": 870,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("device_reference",),
        "example": "判断是否存在故障",
    },
    {
        "rule_id": "action.fault_code.explain_explicit.v1",
        "category": "action_predicate",
        "pattern": r"(?:什么意思|含义|解释|说明|故障码)",
        "semantic_value": "explain_fault_code",
        "priority": 860,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "requires_entity_kind": "fault_code",
        "entity_ref_kinds": ("fault_code",),
        "example": "A07089 是什么意思",
    },
    {
        "rule_id": "action.fault_code.explain_inferred.v1",
        "category": "action_predicate",
        "pattern": r"(?:查询|查一下|查|看看)?[A-Za-z]{1,3}\d{4,6}",
        "semantic_value": "explain_fault_code",
        "priority": 850,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "requires_entity_kind": "fault_code",
        "entity_ref_kinds": ("fault_code",),
        "match_mode": "fullmatch",
        "flags": "IGNORECASE",
        "inferred": True,
        "example": "查询A07089",
    },
    {
        "rule_id": "action.runtime.status.v1",
        "category": "action_predicate",
        "pattern": r"(?:查询|查看|检查|看看|有没有).{0,18}(?:状态|运行|异常|数据)",
        "semantic_value": "check_runtime_status",
        "priority": 840,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "requires_entity_kind": "device_reference",
        "entity_ref_kinds": ("device_reference",),
        "example": "查询G120电机1运行状态",
    },
    {
        "rule_id": "action.workorder.create_draft.v1",
        "category": "action_predicate",
        "pattern": r"(?:创建|生成|新建).{0,5}(?:工单|维修单)",
        "semantic_value": "create_workorder_draft",
        "priority": 830,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("*",),
        "example": "创建维修工单",
    },
)

CAPABILITY_LEXICON = {
    "check_runtime_status": ("action.runtime.status.v1",),
    "compare_runtime_status": ("action.runtime.compare.v1",),
    "create_workorder_draft": ("action.workorder.create_draft.v1",),
    "diagnose_fault": ("action.diagnosis.assess.v1",),
    "explain_fault_code": (
        "action.fault_code.explain_explicit.v1",
        "action.fault_code.explain_inferred.v1",
    ),
    "generate_report": ("action.report.generate.v1",),
    "resolution_recommendation": ("action.recommendation.request.v1",),
}
