"""Declarative rules for deterministic canonical-turn parsing.

This module intentionally contains data only. Rule evaluation belongs to the
entity and clause parser modules.
"""

RULE_CATALOG = (
    {
        "rule_id": "entity.fault_code.shape.v1",
        "category": "fault_code_shape",
        "pattern": r"(?<![A-Za-z0-9])([A-Za-z]{1,3}\d{4,6})(?![A-Za-z0-9])",
        "semantic_value": "fault_code",
        "priority": 700,
        "confidence": 1.0,
        "allowed_clause_roles": ("slot",),
        "capture_group": 1,
        "normalizer": "uppercase",
        "example": "A07089",
    },
    {
        "rule_id": "entity.device.motor_reference.v1",
        "category": "device_pattern",
        "pattern": r"(?<![A-Za-z0-9])(?:(?:[A-Za-z]\d{2,4})?\s*电机\s*\d+|J\d+(?:号机)?)(?!\d)",
        "semantic_value": "device_reference",
        "priority": 690,
        "confidence": 1.0,
        "allowed_clause_roles": ("slot",),
        "flags": "IGNORECASE",
        "normalizer": "remove_spaces",
        "example": "G120电机2",
    },
    {
        "rule_id": "entity.time.relative_window.v1",
        "category": "time_pattern",
        "pattern": (
            r"(?:最近|过去|近)\s*(?:\d+|[一二两三四五六七八九十半]+)\s*(?:分钟|小时|天|周)|"
            r"(?:今天|当前|现在|此刻)"
        ),
        "semantic_value": "time_window",
        "priority": 680,
        "confidence": 1.0,
        "allowed_clause_roles": ("slot",),
        "attributes": {"relative": True},
        "example": "最近一小时",
    },
    {
        "rule_id": "entity.artifact.explicit_reference.v1",
        "category": "artifact_reference",
        "pattern": r"(?<![A-Za-z0-9])(?:artifact|analysis|report|diagnosis):[A-Za-z0-9._:-]+",
        "semantic_value": "artifact_reference",
        "priority": 670,
        "confidence": 1.0,
        "allowed_clause_roles": ("source",),
        "flags": "IGNORECASE",
        "attributes": {"explicit": True},
        "example": "analysis:case-7",
    },
    {
        "rule_id": "source.prior_result.marker.v1",
        "category": "source_marker",
        "pattern": r"(?:(?:刚才|上一轮|上一次|前面|之前|这个|该|已有)(?:的)?|(?<!不)(?:基于|根据|使用|用)(?:刚才的|上一轮的|前面的|这个|已有)?)(?:诊断(?:结果)?|分析结果|运行报告|报告|数据|结果)",
        "semantic_value": "source_reference",
        "priority": 660,
        "confidence": 1.0,
        "allowed_clause_roles": ("source",),
        "attributes": {"historical": True},
        "example": "刚才的诊断结果",
    },
    {
        "rule_id": "reference.correction.marker.v1",
        "category": "correction_marker",
        "pattern": r"(?:不是.+?是|改成|改查|更正为|应该是)",
        "semantic_value": "correction_reference",
        "priority": 650,
        "confidence": 1.0,
        "allowed_clause_roles": ("reference",),
        "example": "改成",
    },
    {
        "rule_id": "reference.deictic.marker.v1",
        "category": "deictic_marker",
        "pattern": r"(?:它|这个|那个|该设备|刚才|上一轮|上一次|前面|之前)",
        "semantic_value": "deictic_reference",
        "priority": 640,
        "confidence": 1.0,
        "allowed_clause_roles": ("reference",),
        "example": "它",
    },
    {
        "rule_id": "clause.boundary.punctuation.v1",
        "category": "clause_boundary",
        "pattern": r"[，,。；;！？!?]+|(?=(?:并|然后|顺便|另外|以及|只|而是|再|最后|接着)(?=(?:和.{0,20})?(?:给(?:出)?|告诉|展示|诊断|分析|查询|查|生成|创建|新建|判断|比较|解释|看看|整理|考虑|安排)))",
        "semantic_value": "boundary",
        "priority": 600,
        "confidence": 1.0,
        "allowed_clause_roles": ("boundary",),
        "example": "，",
    },
    {
        "rule_id": "clause.linker.leading.v1",
        "category": "linker",
        "pattern": r"^(并且|并|然后|同时|顺便|再|另外|以及)\s*",
        "semantic_value": "leading_linker",
        "priority": 590,
        "confidence": 1.0,
        "allowed_clause_roles": ("linker",),
        "capture_group": 1,
        "example": "顺便生成报告",
    },
    {
        "rule_id": "validation.model.forbidden_execution_content.v1",
        "category": "model_validation",
        "pattern": r"(?:\bsql\b|\bnode\b|\btool\b|\bpermission\b|\bauthori[sz](?:e|ation|ed)\b|权限|授权|工具名?|节点名?)",
        "semantic_value": "forbidden_execution_or_authorization_content",
        "priority": 1000,
        "confidence": 1.0,
        "allowed_clause_roles": ("validation",),
        "flags": "IGNORECASE",
        "example": "SQL tool authorization granted",
    },
    {
        "rule_id": "action.workorder.dispatch.v1", "category": "action_predicate",
        "pattern": r"(?:正式|直接|立即|马上|帮我)?.{0,8}(?:派发|派单|下发)(?:工单)?|(?:直接)?安排.{0,8}(?:工程师|人员).{0,8}(?:处理|维修|处置)",
        "semantic_value": "dispatch_workorder", "priority": 930, "confidence": 1.0,
        "allowed_clause_roles": ("action",), "entity_ref_kinds": ("*",),
        "example": "正式派发工单",
    },
    {
        "rule_id": "action.workorder.evaluate.v1", "category": "action_predicate",
        "pattern": r"(?:判断|评估|看看|问问|考虑|知道|想知道)?.{0,14}(?:是否|要不要|有没有|有无|是否需要|是否建议|有没有必要|有必要).{0,14}(?:工单|维修单|报修|建单|安排.{0,4}(?:工程师|人员?).{0,4}处理)|(?:工单|维修单|报修|建单).{0,10}(?:是否需要|有没有必要|有必要|必要性|建议)|(?:评估|判断).{0,8}(?:工单)?必要性|考虑.{0,8}(?:工单|报修)",
        "semantic_value": "evaluate_workorder_need", "priority": 920, "confidence": 1.0,
        "allowed_clause_roles": ("action",), "entity_ref_kinds": ("*",),
        "example": "判断是否需要工单",
    },
    {
        "rule_id": "action.report.generate.v1",
        "category": "action_predicate",
        "pattern": r"(?:生成|整理成?|出一份|制作|整份|给我整).{0,24}(?:运行)?报告|(?:不要|不用|无需|不需要|先别|不必|别).{0,8}(?:生成)?报告",
        "semantic_value": "generate_report",
        "priority": 900,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("*",),
        "example": "生成运行报告",
    },
    {
        "rule_id": "action.recommendation.request.v1",
        "category": "action_predicate",
        "pattern": r"(?:处理建议|处置建议|解决建议|怎么处理|如何处理|给出.{0,4}建议|不需要建议|不用建议)",
        "semantic_value": "resolution_recommendation",
        "priority": 890,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("device_reference",),
        "example": "给出处理建议",
    },
    {
        "rule_id": "action.runtime.compare.v1",
        "category": "action_predicate",
        "pattern": r"(?:对比|比较).{0,36}(?:状态|运行|异常|数据)|(?:对比|比较).{0,36}(?:电机\d+|J\d+).{0,36}(?:电机\d+|J\d+)|和.{0,24}(?:电机\d+|J\d+).{0,12}比较|(?:别|不要|不用).{0,5}(?:对比|比较)",
        "semantic_value": "compare_runtime_status",
        "priority": 880,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("device_reference",),
        "example": "对比运行状态",
    },
    {
        "rule_id": "action.diagnosis.assess.v1",
        "category": "action_predicate",
        "pattern": r"(?:诊断(?!结果)(?:一下|看看)?|判断|排查|分析).{0,24}(?:故障|异常|问题|原因|根因|[A-Za-z]{1,3}\d{4,6})|(?:运行数据|运行状态).{0,12}(?:判断|诊断|分析)|(?:详细)?诊断(?!结果)(?:一下|看看)?|继续分析|(?:为什么|为何).{0,18}(?:故障|异常|问题)|(?:有没有|是否|存在|是不是).{0,8}(?:故障|异常|问题|不太对劲|毛病)|(?:故障|异常)吗|(?:如果|若).{0,12}(?:故障|异常|问题)$|(?:不用|无需|不必|不要).{0,5}(?:重新)?诊断",
        "semantic_value": "diagnose_fault",
        "priority": 878,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("device_reference",),
        "example": "判断是否存在故障",
    },
    {
        "rule_id": "action.fault_code.explain_explicit.v1",
        "category": "action_predicate",
        "pattern": r"(?:是什么|什么意思|含义|解释|说明|故障码)",
        "semantic_value": "explain_fault_code",
        "priority": 860,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "requires_entity_kind": "fault_code",
        "entity_ref_kinds": ("fault_code",),
        "example": "A07089 是什么意思",
    },
    {
        "rule_id": "action.fault_code.explain_inferred.v1",
        "category": "action_predicate",
        "pattern": r"(?:查询|查一下|查|看看)?[A-Za-z]{1,3}\d{4,6}",
        "semantic_value": "explain_fault_code",
        "priority": 850,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "requires_entity_kind": "fault_code",
        "entity_ref_kinds": ("fault_code",),
        "match_mode": "fullmatch",
        "flags": "IGNORECASE",
        "inferred": True,
        "example": "查询A07089",
    },
    {
        "rule_id": "action.runtime.status.v1",
        "category": "action_predicate",
        "pattern": r"(?<!排)(?:查询|查看|检查|看看|查|改查|展示|告诉我).{0,24}(?:状态|运行|异常|数据|电机\d+)|查完.{0,16}(?:J\d+|电机\d+)|(?:当前|现在|最近).{0,18}(?:状态|运行|异常|健康|咋样)|(?:健康状况|运行情况|最近咋样)|(?:不用|无需|不必|不要).{0,8}(?:重新)?查询",
        "semantic_value": "check_runtime_status",
        "priority": 879,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("device_reference",),
        "example": "查询G120电机1运行状态",
    },
    {
        "rule_id": "action.workorder.create_draft.v1",
        "category": "action_predicate",
        "pattern": r"(?:创建|生成|新建).{0,24}(?:工单|维修单|草稿)|(?:不要|不用|无需|不需要|先别|不是要|不必|别).{0,10}(?:创建|生成|新建|执行)?(?:工单|维修单|草稿)",
        "semantic_value": "create_workorder_draft",
        "priority": 885,
        "confidence": 1.0,
        "allowed_clause_roles": ("action",),
        "entity_ref_kinds": ("*",),
        "example": "创建维修工单",
    },
)

CAPABILITY_LEXICON = {
    "check_runtime_status": ("action.runtime.status.v1",),
    "compare_runtime_status": ("action.runtime.compare.v1",),
    "create_workorder_draft": ("action.workorder.create_draft.v1",),
    "dispatch_workorder": ("action.workorder.dispatch.v1",),
    "evaluate_workorder_need": ("action.workorder.evaluate.v1",),
    "diagnose_fault": ("action.diagnosis.assess.v1",),
    "explain_fault_code": (
        "action.fault_code.explain_explicit.v1",
        "action.fault_code.explain_inferred.v1",
    ),
    "generate_report": ("action.report.generate.v1",),
    "resolution_recommendation": ("action.recommendation.request.v1",),
}
