"""MCP tool handlers."""

from .handlers import (
    analyze_fault_handler,
    analyze_metric_trend_handler,
    create_work_order_draft_handler,
    diagnose_fault_handler,
    explain_fault_code_handler,
    generate_diagnosis_artifact_handler,
    get_equipment_snapshot_handler,
    get_equipment_info_handler,
    get_equipment_status_handler,
    get_fault_context_handler,
    generate_diagnosis_report_handler,
    list_equipment_handler,
    query_alarm_history_handler,
    query_equipment_data_handler,
    query_equipment_metrics_handler,
    query_event_history_handler,
    query_fault_history_handler,
    query_metric_trend_handler,
    rank_possible_causes_handler,
    retrieve_fault_knowledge_handler,
    search_fault_knowledge_handler,
    suggest_fault_actions_handler,
)

__all__ = [
    "analyze_fault_handler",
    "analyze_metric_trend_handler",
    "create_work_order_draft_handler",
    "diagnose_fault_handler",
    "explain_fault_code_handler",
    "generate_diagnosis_artifact_handler",
    "get_equipment_snapshot_handler",
    "get_equipment_info_handler",
    "get_equipment_status_handler",
    "get_fault_context_handler",
    "generate_diagnosis_report_handler",
    "list_equipment_handler",
    "query_alarm_history_handler",
    "query_equipment_data_handler",
    "query_equipment_metrics_handler",
    "query_event_history_handler",
    "query_fault_history_handler",
    "query_metric_trend_handler",
    "rank_possible_causes_handler",
    "retrieve_fault_knowledge_handler",
    "search_fault_knowledge_handler",
    "suggest_fault_actions_handler",
]
